import type { Metadata } from "next";
import { Barlow_Condensed } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import localfont from "next/font/local";
import ReduxProvider from "../redux/provider";
import SessionWrapper from "../../components/SessionWrapper";

// Configure Barlow Condensed font
const barlow = Barlow_Condensed({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700"],
  variable: "--font-barlow",
});

// Configure local Founders font
const founders = localfont({
  src: [
    {
      path: "../../public/fonts/FoundersGroteskXCond-Lt.woff2",
      weight: "200",
    },
  ],
  variable: "--font-founders",
});

// Define metadata for the application
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// Layout component that applies fonts and provides Redux context
export default function Layout({ children }: { children: React.ReactNode }) {
  return (
    <SessionWrapper>
      <html lang="en">
        <body
          className={cn(
            "bg-background min-h-screen antialiased",
            barlow.className,
            founders.variable // Apply Founders font variable
          )}
        >
          <ReduxProvider>{children}</ReduxProvider>
        </body>
      </html>
    </SessionWrapper>
  );
}
